import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css"
// import { FaArrowCircleRight } from "react-icons/fa";
import Link from "next/link";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.navContainer}>
          <div className={styles.nav}>
            <div className={styles.navLinks}>
              <a href="./">Home </a>

              <div className={styles.bottomLinksContainer}>
                <Link href={'/projects'} className={styles.bottomLink}>Portfolio Projects</Link>
                <a href="/AboutMe" className={styles.bottomLink}> About me</a>
              </div>
            </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
